name: Python Lint and Format

on:
  push:
    paths:
      - "**/*.py"
  pull_request:
    paths:
      - "**/*.py"

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autoflake isort pyupgrade black

      - name: Run autoflake
        run: |
          autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place .

      - name: Run isort
        run: |
          isort .

      # - name: Run pyupgrade
      #   run: |
      #     pyupgrade --py37-plus $(find . -name "*.py")

      - name: Run Black
        run: |
          black .

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Apply autoflake, isort, pyupgrade, and Black" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
